version: '3'
services:
  # nginx servers static files and is a proxy for api-endpoint
  nginx-entry:
    build: nginx
    ports:
      - '80:80'
    depends_on:
      - uwsgi
      - lychee

  lychee:
    image: "kdelfour/lychee-docker"
    
  uwsgi:
    build: uwsgi-api-server
    depends_on:
      - mongo
  mongo:
    image: mongo

  mongo-backup:
    image: "istepanov/mongodump:3.4"
    volumes:
      - mongo-backup:/backup
    environment:
      CRON_SCHEDULE: '0 1 * * *'
    depends_on:
      - mongo
volumes:
  mongo-backup:
