version: '3'
services:
  # nginx servers static files and is a proxy for api-endpoint
  nginx-entry:
    build: nginx
    ports:
      - '80:80'
    depends_on:
      - uwsgi
  uwsgi:
    build: uwsgi-api-server
    depends_on:
      - mongo
  mongo:
    image: mongo
