version: '3'
services:
  # nginx servers static files and is a proxy for api-endpoint
  nginx-endpoint:
    build: nginx
    ports:
      - '80:80'
  api-endpoint:
    build: uwsgi-api-server
    # ports:
    #   - '80:5000'
  mongo:
    image: mongo
